nexus/usecases/intelligences/__init__.py, nexus/usecases/intelligences/list.py, nexus/usecases/intelligences/tests/test_list_intelligence.py, nexus/usecases/orgs/__init__.py, nexus/usecases/orgs/exceptions.py, nexus/usecases/orgs/get_by_uuid.py, nexus/usecases/orgs/tests/test_get_by_uuid.py
Add new org usecases:
- Exception: Handle organization issues
- Get_by_uuid: Filter org by uuid
Add new intelligence usecases:
- List intelligences by org
=> Add new usecases that List Intelligence by org

nexus/intelligences/api/tests/test_views.py, nexus/intelligences/api/views.py, nexus/usecases/intelligences/__init__.py, nexus/usecases/intelligences/delete.py, nexus/usecases/intelligences/tests/test_delete_intelligence.py
Add new Update API method using intelligence usecase
=> feat: Update Intelligence API Method

nexus/intelligences/api/serializers.py, nexus/intelligences/api/tests/test_views.py, nexus/intelligences/api/views.py, nexus/usecases/intelligences/__init__.py
Add: ContentBase CRUD api
Add: New options for pagination
=> Feat: API CRUD ContentBase

nexus/intelligences/api/routers.py, nexus/intelligences/api/serializers.py, nexus/intelligences/api/tests/test_views.py, nexus/intelligences/api/views.py, nexus/usecases/intelligences/__init__.py, nexus/usecases/intelligences/create.py, nexus/usecases/intelligences/delete.py, nexus/usecases/intelligences/exceptions.py, nexus/usecases/intelligences/get_by_uuid.py, nexus/usecases/intelligences/list.py, nexus/usecases/intelligences/tests/intelligence_factory.py, nexus/usecases/intelligences/tests/test_create_intelligence.py, nexus/usecases/intelligences/tests/test_delete_intelligence.py, nexus/usecases/intelligences/tests/test_get_by_uuid.py, nexus/usecases/intelligences/tests/test_list_intelligence.py, nexus/usecases/intelligences/tests/test_update_intelligence.py, nexus/usecases/intelligences/update.py, nexus/usecases/orgs/tests/org_factory.py, nexus/usecases/orgs/tests/test_get_by_uuid.py, nexus/usecases/users/tests/test_get_by_uuid.py, nexus/usecases/users/tests/user_factory.py
Add ContentBase CRUD useses, tests and exceptions.
=> Feature: ContentBase CRUD usecases

nexus/intelligences/api/tests/test_views.py, nexus/intelligences/api/views.py, nexus/task_managers/tasks.py, nexus/usecases/intelligences/__init__.py, nexus/usecases/intelligences/get_by_uuid.py, nexus/usecases/intelligences/tests/test_get_by_uuid.py
Add sentenx upload for updating content base text objects.
=> Fix: Missing indexer on update text

nexus/intelligences/api/tests/test_views.py, nexus/intelligences/api/views.py, nexus/usecases/intelligences/tests/intelligence_factory.py, nexus/usecases/intelligences/tests/test_update_intelligence.py, nexus/usecases/intelligences/update.py
Add missing update language on contentbase patch api method.
=> Fix: Missing update language

nexus/intelligences/api/views.py
=> Fix: Missing description request data

.coveragerc, nexus/task_managers/file_manager/tests/test_celery_file_manager.py, nexus/usecases/intelligences/list.py, nexus/usecases/intelligences/tests/intelligence_factory.py, nexus/usecases/intelligences/tests/test_list_intelligence.py, nexus/usecases/orgs/get_by_uuid.py, nexus/usecases/orgs/tests/test_get_by_uuid.py, nexus/usecases/orgs/tests/test_get_org_auth.py, nexus/usecases/projects/tests/project_factory.py, nexus/usecases/projects/tests/test_create_project.py, nexus/usecases/projects/tests/test_get_by_uuid.py, nexus/usecases/task_managers/celery_task_manager.py, nexus/usecases/task_managers/tests/task_manager_factory.py, nexus/usecases/task_managers/tests/test_celery_manager.py, nexus/usecases/template_type/template_type_usecase.py, nexus/usecases/template_type/tests/template_type_factory.py, nexus/usecases/template_type/tests/test_template_type.py, nexus/users/tests/test_models.py
Create factories and add missing unittests.
=> Fix: Adding missing unittests

nexus/intelligences/api/views.py, nexus/task_managers/file_database/sentenx_file_database.py, nexus/task_managers/file_manager/celery_file_manager.py, nexus/task_managers/tasks.py
Create loader types on SentenX request
=> Add: Loader type on sentenx classification

nexus/actions/tests.py, nexus/intelligences/api/tests/test_views.py, nexus/projects/api/routers.py, nexus/projects/api/serializers.py, nexus/projects/api/tests/test_views.py, nexus/projects/api/views.py, nexus/projects/project_dto.py, nexus/urls.py, nexus/usecases/intelligences/__init__.py, nexus/usecases/intelligences/create.py, nexus/usecases/intelligences/get_by_uuid.py, nexus/usecases/intelligences/list.py, nexus/usecases/intelligences/tests/intelligence_factory.py, nexus/usecases/intelligences/tests/test_create_intelligence.py, nexus/usecases/intelligences/tests/test_get_by_uuid.py, nexus/usecases/intelligences/tests/test_list_intelligence.py, nexus/usecases/intelligences/tests/test_update_intelligence.py, nexus/usecases/projects/__init__.py, nexus/usecases/projects/dto.py, nexus/usecases/projects/get_by_uuid.py, nexus/usecases/projects/tests/project_factory.py, nexus/usecases/projects/tests/test_create_project.py, nexus/usecases/projects/tests/test_update.py, nexus/usecases/projects/update.py
Add Brain on status, a message to EDA will be sent on next updates.
=> Feature: Brain_on status

router/clients/flows/http/__init__.py, router/clients/flows/http/broadcast.py, router/clients/flows/http/flow_start.py, router/direct_message/__init__.py, router/direct_message/exceptions.py, router/direct_message/interfaces.py, router/flow_start/__init__.py, router/flow_start/exceptions.py, router/flow_start/interfaces.py
These clients were created using a scalable design and allow you to use them via dependency inversion.
```py
from router.direct_message import DirectMessage
from router.flow_start import FlowStart
def route(direct_message: DirectMessage, flow_start: FlowStart):
if have_flow:
flow_start.start_flow(flow=<FLOW_UUID>, user=<USER_EMAIL>, urns=[<URN>])
else:
direct_message.send_direct_message(text="hello", urns=[<URN>], project_uuid=<PROJECT_UUID>, user=<USER_EMAIL>)
from router.clients.flows.http import BroadcastHTTPClient, FlowStartHTTPClient
def dispatch(...):
direct_message_client = BroadcastHTTPClient("http://fakehost.com", "ABCDEFG")
flow_start_client = FlowStartHTTPClient("http://fakehost.com", "ABCDEFG")
route(direct_message_client, flow_start_client)
```
=> Create Flows clients that allows to start a flows and broadcasts

nexus/usecases/intelligences/get_by_uuid.py
implement create IntegratedIntelligence
=> Fix: Integrated intelligence not created

nexus/usecases/__init__.py, nexus/usecases/event_driven/__init__.py, nexus/usecases/event_driven/mocks.py, nexus/usecases/event_driven/publishers_dto.py, nexus/usecases/event_driven/recent_activities.py, nexus/usecases/intelligences/__init__.py, nexus/usecases/intelligences/create.py, nexus/usecases/intelligences/publishers_msg.py, nexus/usecases/intelligences/tests/test_create_intelligence.py
Send message on certain events in rabbitmq.
=> Add: Recent activities message

contrib/gen_env.py, nexus/actions/tests.py, nexus/intelligences/api/tests/test_views.py, nexus/intelligences/api/views.py, nexus/intelligences/tests/test_models.py, nexus/usecases/intelligences/create.py, nexus/usecases/intelligences/tests/intelligence_factory.py, nexus/usecases/intelligences/tests/test_create_intelligence.py, nexus/usecases/intelligences/tests/test_search.py, nexus/usecases/logs/tests/message_factory.py, nexus/usecases/projects/projects_use_case.py, nexus/usecases/projects/tests/test_create_project.py, nexus/usecases/task_managers/tests/test_wenigpt_db.py, nexus/usecases/users/tests/user_factory.py
This branch will fix most of the rabbitmq connection trials thas had generated errors on CI testing. Dependency injection pattern will be used.
=> Fix: Unittest errors

nexus/projects/exceptions.py, nexus/projects/permissions.py, nexus/usecases/intelligences/list.py, nexus/usecases/intelligences/retrieve.py, nexus/usecases/intelligences/update.py
Change brain to work using project permissions instead of organization permission.
=> Update: Change brain default permission

.coveragerc, nexus/actions/api/views.py, nexus/event_domain/recent_activity/external_activities.py, nexus/usecases/actions/tests/flow_factory.py, router/classifiers/chatgpt_function.py, router/classifiers/interfaces.py, router/classifiers/mocks.py, router/classifiers/tests.py, router/classifiers/zeroshot.py, router/tasks/tasks.py
Improve classifiers code using dependecy injection. Create tests to improve coverage.
=> Feature: Classifier refactor

nexus/actions/api/views.py, nexus/projects/permissions.py
Change the current OrgAuth used on action management to use ProjectAuth
=> Fix: Wrong auth used on api

nexus/intelligences/api/routers.py, nexus/intelligences/api/views.py, nexus/task_managers/file_database/sentenx_file_database.py
Add an API that brings a preview of indexed content on SentenX aplication.
=> Feature: Document preview

router/repositories/orm/__init__.py
Fix message bringing the first five messages from the contact instead of the five last messages.
=> Fix: Message order

nexus/orgs/tests/test_permissions.py, nexus/projects/permissions.py, nexus/projects/tests/test_permissions.py
Improve current exiting permissions unittests and add missing ones.
=> Fix: Missing permission unittests

nexus/intelligences/api/views.py
Validate if the project and the contentbase are from the same organization.
=> Fix: Document preview permissions

nexus/intelligences/api/serializers.py, nexus/intelligences/tests/test_serializers.py, nexus/usecases/intelligences/create.py, nexus/usecases/intelligences/tests/test_create_intelligence.py, nexus/usecases/intelligences/update.py
Return created_at on most of the intelligences views. Also create a default personality whenever creating an brain structure.
=> Feature: Return more data on intelligences views

nexus/usecases/projects/update.py
Change organization permission check to project permission validation.
=> Change default permission

nexus/intelligences/models.py, nexus/intelligences/tests/test_models.py
Missing rule where a project can have only one Intelligence with is_router True.
=> Fix: Integrity error

nexus/usecases/projects/projects_use_case.py, nexus/usecases/projects/tests/test_create_project.py
Missing statement on the updated project usecase creation
=> Fix: Missing brain_on statement

nexus/usecases/intelligences/create.py, router/route.py
Currently the language on some models are always setting up as "pt-br".
=> Fix: Temporarily remove language instruction

nexus/projects/consumers/integrated_feature.py, nexus/projects/handle.py, nexus/projects/models.py, nexus/usecases/actions/update.py, nexus/usecases/projects/create.py, nexus/usecases/projects/delete.py, nexus/usecases/projects/dto.py, nexus/usecases/projects/tests/test_create_project.py, nexus/usecases/projects/tests/test_update.py, nexus/usecases/projects/update.py
Add update function to existing IntegratedFeature and handle Flow updates as well.
=> Feature: Update retail

nexus/logs/api/serializers.py, router/classifiers/groundedness.py
Regex not capturing not found sentence evidences
=> Fix: Reflection errors

nexus/actions/api/views.py, nexus/actions/tests.py, nexus/usecases/actions/tests/test_update.py, nexus/usecases/actions/update.py, nexus/usecases/projects/create.py, nexus/usecases/projects/dto.py
Add new dto to integrated_feature flows, and add the possibility to change flow_uuid on viewset usage.
=> Feature: Update flow_uuid on actions

nexus/agents/api/views.py
* * [x] Bugfix
* * [ ] Feature
* * [ ] Code style update (formatting, local variables)
* * [ ] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
The way agent credentials were created did not replicate the credential properties for projects where the agent was not created, resulting in a "duplication" bug of these credentials.
- Replaced the loop iterating over credentials_data.items() with a more structured approach using a list of credential objects.
- Changed the credential creation logic to use get_or_create, avoiding duplicate entries.
- Added proper handling of credential attributes (label, placeholder, is_confidential, and value).
=> [NEXUS-2696] - Enhance project credentials creation and update logic at post

nexus/agents/api/views.py, nexus/task_managers/file_database/bedrock.py, nexus/usecases/agents/agents.py
- Restructured PushAgents view to improve modularity and error handling
- Added comprehensive logging and error tracking for agent and skill creation/updates
- Implemented rollback mechanism for failed agent creation
- Added new methods to handle agent creation, update, and skill processing
- Enhanced error response and logging in agent push endpoint
=> Refactor agent push process with improved error handling and logging

router/tasks/tasks.py
Handle messages sent before the agent be capeable of answering
=> Add: Multiple messages support

nexus/intelligences/consumers/conversation_consumer.py, nexus/intelligences/models.py, nexus/usecases/inline_agents/create.py, nexus/usecases/intelligences/lambda_usecase.py
Enhancement
___
- Add start_date and end_date fields to Conversation model
- Update conversation creation to include date range parameters
- Remove deprecated message-related methods from model
- Clean up TODO comments in consumer code
___
```mermaid
flowchart LR
A["Consumer Message"] --> B["WindowConversationDTO"]
B --> C["LambdaUseCase"]
C --> D["CreateConversationUseCase"]
D --> E["Conversation Model"]
E --> F["Database with start_date/end_date"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Miscellaneous</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>conversation_consumer.py</strong><dd><code>Clean up TODO comment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> adding start date and end date and the migration

nexus/usecases/intelligences/lambda_usecase.py
Bug fix
___
- Fix lambda response parsing by reading Payload stream
- Add debug logging for lambda response structure
___
```mermaid
flowchart LR
A["Lambda Invocation"] --> B["Get Payload Stream"]
B --> C["Read and Parse JSON"]
C --> D["Extract Body Response"]
```
<tr>
<td>
<details>
<summary><strong>lambda_usecase.py</strong><dd><code>Fix lambda response payload parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
nexus/usecases/intelligences/lambda_usecase.py …
=> changing get response

inline_agents/backends/bedrock/adapter.py, inline_agents/backends/bedrock/backend.py, inline_agents/backends/bedrock/tests/test_adapter.py, inline_agents/backends/bedrock/tests/traces_factory.py
Tests, Enhancement
___
- Add comprehensive unit tests for custom event data processing
- Refactor custom event handling into dedicated adapter method
- Create CustomEventTraceFactory for test data generation
- Improve code organization by extracting inline logic
___
```mermaid
flowchart LR
A["Backend invoke_agents"] --> B["Adapter custom_event_data"]
B --> C["Parse action group output"]
C --> D["Send to data lake"]
E["CustomEventTraceFactory"] --> F["Unit Tests"]
F --> G["Test Coverage"]
```
<tr>
<td>
<details>
<summary><strong>adapter.py</strong><dd><code>Extract custom event processing into …
=> Feauture: Unittests datalake

nexus/task_managers/tasks.py
Bug fix
___
- Pass file name parameter to `s3FileDatabase().add_file()` method
___
```mermaid
flowchart LR
A["upload_text_file function"] --> B["s3FileDatabase().add_file()"]
B --> C["Include file_name parameter"]
```
<tr>
<td>
<details>
<summary><strong>tasks.py</strong><dd><code>Add file name parameter to S3 upload</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
nexus/task_managers/tasks.py
<ul><li>Modified <code>s3FileDatabase().add_file()</code> call to include …
=> Update file upload function to include file name

inline_agents/backends/bedrock/adapter.py
Enhancement
___
- Add channel parameter to session attributes
- Update inline session state method signature
- Include channel UUID in Bedrock adapter configuration
___
```mermaid
flowchart LR
A["to_external method"] --> B["_get_inline_session_state"]
B --> C["session_attributes"]
C --> D["channel UUID added"]
```
<tr>
<td>
<details>
<summary><strong>adapter.py</strong><dd><code>Add channel parameter to session state</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Add channel parameter to session attributes

inline_agents/backends/bedrock/backend.py, nexus/usecases/inline_agents/typing.py, router/tasks/invoke.py
Enhancement
___
- Remove channel-specific filtering for typing indicators
- Pass preview parameter to typing message method
- Clean up debug print statements
- Standardize typing indicator behavior across channels
___
```mermaid
flowchart LR
A["TypingUsecase"] --> B["Remove WhatsApp filter"]
B --> C["Accept preview parameter"]
C --> D["Unified typing behavior"]
E["Backend calls"] --> F["Pass preview parameter"]
F --> G["Remove debug prints"]
```
<tr>
<td>
<details>
<summary><strong>backend.py</strong><dd><code>Update typing calls and remove debug prints</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Remove filter by channel on typing

nexus/intelligences/api/routers.py, nexus/intelligences/api/views.py, nexus/task_managers/file_manager/celery_file_manager.py, nexus/task_managers/tasks.py, nexus/task_managers/tasks_bedrock.py, nexus/usecases/intelligences/list.py, nexus/usecases/intelligences/retrieve.py, nexus/usecases/intelligences/update.py
Enhancement
___
- Add new inline content base file endpoint with project-based authentication
- Implement CRUD operations for inline file management
- Support both Bedrock and SentenX indexer databases
- Add specialized task handlers for inline file processing
___
```mermaid
flowchart LR
A["Project UUID"] --> B["InlineContentBaseFileViewset"]
B --> C["File Upload"]
B --> D["File Retrieval"]
B --> E["File Deletion"]
C --> F["CeleryFileManager"]
F --> G["Bedrock Database"]
F --> H["SentenX Database"]
G --> I["bedrock_upload_inline_file task"]
H --> J["upload_sentenx_inline_file task"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody></tr></tbody></table>
</details>
___
=> Feature: New inline content base file endpoint

router/tasks/invoke.py, router/traces_observers/save_traces.py
Enhancement
___
- Add contact_urn tag to Sentry for better filtering
- Implement error handling with comprehensive context in trace saving
- Add debug information for troubleshooting trace events
___
```mermaid
flowchart LR
A["Task Invocation"] --> B["Add contact_urn tag"]
C["Trace Saving"] --> D["Wrap in try-catch"]
D --> E["Add Sentry context on error"]
E --> F["Include trace events data"]
```
<tr>
<td>
<details>
<summary><strong>invoke.py</strong><dd><code>Add contact_urn Sentry tag</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Improve debug tags and filters

inline_agents/backends/bedrock/adapter.py, inline_agents/backends/bedrock/backend.py, nexus/usecases/inline_agents/update.py
Enhancement
___
- Add agent UUID to event metadata for tracking
- Extract collaborator name from trace events
- Refactor conversation updates to use dedicated function
- Improve metadata handling with null checks
___
```mermaid
flowchart LR
A["Trace Event"] --> B["Extract Collaborator Name"]
B --> C["Get Agent UUID"]
C --> D["Add to Metadata"]
D --> E["Update Conversation"]
E --> F["Send to Data Lake"]
```
<tr>
<td>
<details>
<summary><strong>adapter.py</strong><dd><code>Add agent UUID metadata and refactor updates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Feature: Add agent uuid on metadata

inline_agents/backends/openai/adapter.py, inline_agents/backends/openai/backend.py, nexus/event_domain/event_manager.py, nexus/events.py, nexus/projects/websockets/consumers.py, router/traces_observers/save_traces.py, router/traces_observers/summary.py
- Updated OpenAITeamAdapter to ensure agent names are standardized.
- Introduced StreamEventLogger for capturing and saving stream events in JSON format.
- Implemented process_openai_trace function to standardize event handling.
- Enhanced OpenAIBackend to log events and notify observers asynchronously.
- Added AsyncSummaryTracesObserver for handling trace updates in async contexts.
___
Enhancement
___
- Add comprehensive event processing and logging for OpenAI backend
- Implement async trace observers for real-time event handling
- Standardize agent naming with `_agent` suffix convention
- Create stream event capture and JSON logging system
___
```mermaid
flowchart LR
A["OpenAI Events"] --> B["StreamEventLogger"]
B --> C["process_openai_trace"]
C --> D["Standardized Events"]
D --> …
```
=> Add event processing and logging for OpenAI backend

inline_agents/backends/openai/backend.py
Bug fix
___
- Fixed incorrect variable assignment in OpenAI backend
- Changed `contact_urn` parameter from `sanitized_urn` to `contact_urn`
___
```mermaid
flowchart LR
A["OpenAI Backend"] --> B["team_adapter.to_external()"]
B --> C["contact_urn parameter"]
C --> D["Fixed: sanitized_urn → contact_urn"]
```
<tr>
<td>
<details>
<summary><strong>backend.py</strong><dd><code>Fix contact_urn parameter assignment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Fix: Corrected contact_urn assignment in OpenAIBackend

nexus/usecases/intelligences/lambda_usecase.py
Bug fix
___
- Fix external_id parameter mapping in lambda conversation
- Reorder task manager cache clearing operation
___
```mermaid
flowchart LR
A["Payload Input"] --> B["Resolution DTO Creation"]
B --> C["Fix external_id mapping"]
C --> D["Resolution Message"]
D --> E["Clear Message Cache"]
```
<tr>
<td>
<details>
<summary><strong>lambda_usecase.py</strong><dd><code>Fix external_id parameter and reorder cache clearing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
nexus/usecases/intelligences/lambda_usecase.py
<ul><li>Fix external_id parameter from <code>payload.get("id")</code> to …
=> fix external id

nexus/inline_agents/api/views.py
Enhancement
___
- Updated permission class for multi-agent endpoint
- Replaced dual permission classes with combined permission
- Added new import for external project permission
___
```mermaid
flowchart LR
A["MultiAgentView"] --> B["Permission Update"]
B --> C["CombinedExternalProjectPermission"]
D["IsAuthenticated + ProjectPermission"] --> C
```
<tr>
<td>
<details>
<summary><strong>views.py</strong><dd><code>Update multi-agent view permission class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Change multi agent permission

nexus/cache/__init__.py, nexus/cache/token.py, nexus/internals/__init__.py, nexus/usecases/inline_agents/typing.py
Enhancement
___
- Implements token caching system for Keycloak authentication
- Adds automatic retry mechanism for authentication failures
- Improves typing indicator service with better error handling
- Replaces print statements with proper logging
___
```mermaid
flowchart LR
A["TokenCache"] --> B["InternalAuthentication"]
B --> C["TypingUsecase"]
B --> D["Keycloak Token API"]
C --> E["WhatsApp Broadcasts API"]
B -- "retry on 401/403" --> E
```
<tr>
<td>
<details>
<summary><strong>__init__.py</strong><dd><code>Initialize cache module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> fix: adds cache for keycloak token

poetry.lock, pyproject.toml
Other
___
- Update litellm dependency to version 1.76.3
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pyproject.toml</strong><dd><code>Add litellm dependency version 1.76.3</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
pyproject.toml
- Added litellm dependency with version 1.76.3
</details>
</td>
<td><a href="https://github.com/weni-ai/nexus-ai/pull/777/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
=> update litellm to 1.76.3

inline_agents/backends/openai/hooks.py
Bug fix, Enhancement
___
- Remove unnecessary metadata from action group invocation output
- Fix condition in SupervisorHooks for tool name checking
- Add tool name parameter to send_trace method calls
___
```mermaid
flowchart LR
A["Action Group Output"] --> B["Remove Metadata Field"]
C["Tool Name Check"] --> D["Fix Logic Condition"]
E["Send Trace Method"] --> F["Add Tool Name Parameter"]
```
<tr>
<td>
<details>
<summary><strong>hooks.py</strong><dd><code>Fix hooks metadata and tool name handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Feature/save OpenAI traces s3

inline_agents/backends/bedrock/adapter.py, inline_agents/backends/bedrock/backend.py, inline_agents/backends/openai/adapter.py, inline_agents/backends/openai/hooks.py
Enhancement
___
- Add foundation model and backend parameters to data lake events
- Update adapter method signature with new metadata fields
- Pass agent model information to event tracking calls
___
```mermaid
flowchart LR
A["Agent Hook Calls"] --> B["Data Lake Event Adapter"]
B --> C["Event Metadata"]
C --> D["Backend: 'openai'"]
C --> E["Foundation Model: agent.model"]
```
<tr>
<td>
<details>
<summary><strong>adapter.py</strong><dd><code>Extend adapter with metadata parameters</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> send foundation model and backend in data lake event metadata

nexus/usecases/intelligences/get_by_uuid.py
Bug fix
___
- Fix deletion of duplicate IntegratedIntelligence objects
- Replace queryset delete with filtered delete by IDs
___
```mermaid
flowchart LR
A["Duplicate Objects"] --> B["Extract IDs"] --> C["Filter by IDs"] --> D["Delete Objects"]
```
<tr>
<td>
<details>
<summary><strong>get_by_uuid.py</strong><dd><code>Fix duplicate object deletion method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
nexus/usecases/intelligences/get_by_uuid.py
<ul><li>Replace direct queryset delete …
=> Fix IntegratedIntelligence multiple objects
